name: flutter_auth
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.9.43+145

environment:
  sdk: ">=2.18.2 <3.3.9"

dependencies:
  back_button_interceptor: ^6.0.1
  bubble: ^1.2.1
  # carousel_pro: ^1.0.0
  another_carousel_pro: ^1.0.2
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.5
  datetime_picker_formfield: ^2.0.1
  dio: ^4.0.6
  # fijkplayer: ^0.10.1
  # fijkplayer_update: ^1.1.1
  # firebase_core: ^1.21.0
  firebase_core: ^2.1.1
  # firebase_database: ^9.1.2
  # firebase_messaging: ^12.0.3
  
  firebase_messaging: ^14.0.4
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.4
  getwidget: ^3.0.1
  # giffy_dialog: ^1.8.0
  # giffy_dialog: ^2.3.0
  gradient_borders: ^0.2.0
  http: ^0.13.5
  intl: ^0.17.0
  # liquid_progress_indicator: ^0.4.0
  liquid_progress_indicator_v2: ^0.5.0
  localstorage: ^4.0.0+1
  lottie: ^1.4.2
  # package_info: ^2.0.2
  package_info_plus: ^4.2.0
  provider: ^6.0.2
  qr_flutter: ^4.0.0
  # rate_my_app: ^1.1.3
  rate_my_app: ^2.1.0
  rxdart: ^0.27.5
  # shared_preferences: ^2.0.15
  shared_preferences: ^2.2.3
  socket_io_client: ^1.0.1
  # splashscreen: ^1.3.5
  another_flutter_splash_screen: ^1.2.1
  quickalert: ^1.1.0
  # url_launcher: ^6.1.5
  url_launcher: ^6.3.0
  # video_player: ^2.4.7
  video_player: ^2.9.2
  # flutter_neumorphic: ^3.2.0
  flutter_neumorphic_plus: ^3.4.0
  upgrader: ^6.4.0
  flutter_launcher_icons: ^0.10.0
  font_awesome_flutter: ^9.2.0
  dotted_line: ^3.2.2
  permission_handler: ^11.0.1
  # app_settings: ^4.2.0
  app_settings: ^6.1.1
  event_bus: ^2.0.0
  # record: ^4.4.4
  record: ^5.1.2
  # path_provider: ^2.0.15
  path_provider: ^2.1.4
  # audioplayers: ^4.1.0
  audioplayers: ^6.1.0
  #flutter_ffmpeg: ^0.4.2
  # geolocator: ^7.6.2
  geolocator: ^11.0.0
  device_info_plus: ^9.1.2
  mqtt_client: ^9.8.1
  # flutter_background_service: ^5.1.0
  # flutter_local_notifications: ^9.5.3+1
  flutter_local_notifications: ^17.2.4
  logger: ^2.5.0
  connectivity_plus: ^5.0.2
  battery_plus: ^5.0.3
  # flutter_webrtc: ^0.9.34  
  audio_session: ^0.1.20
  # jitsi_meet: ^4.0.0
  jitsi_meet_flutter_sdk: ^11.3.0
  # android_intent_plus: ^5.2.1
  
  
dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: 'launcher_icons'
  ios: true
  image_path: 'assets/images/travel.png'
  adaptive_icon_background: 'assets/images/travel.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
