
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
    
    // Inyectar flutter globals para plugins como geolocator_android que no están 100% actualizados a declarativo
    project.ext.flutter = [
        compileSdkVersion: 35,
        minSdkVersion: 26,
        targetSdkVersion: 35
    ]
}

subprojects {
    if (project.name == 'app' || project.state.executed) return
    project.afterEvaluate {
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    namespace project.group
                }
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

